language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-28
  licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
before_script:
- wget http://services.gradle.org/distributions/gradle-4.10.1-bin.zip
- unzip gradle-4.10.1-bin.zip
- export GRADLE_HOME=$PWD/gradle-4.10.1
- export PATH=$GRADLE_HOME/bin:$PATH
script:
- gradle build connectedCheck